# Generated by Django 4.2 on 2023-05-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type_code", models.BigIntegerField(auto_created=True)),
                ("event_code", models.BigIntegerField(auto_created=True)),
                ("event_name", models.CharField(max_length=100)),
                ("event_type_name", models.CharField(max_length=100)),
                ("event_demography", models.CharField(max_length=100)),
                ("event_demography_code", models.CharField(max_length=100)),
            ],
        ),
    ]
