# Generated by Django 4.2 on 2023-05-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomCateory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomcategory_name", models.CharField(max_length=100)),
                ("roomcategory_code", models.BigIntegerField()),
                ("max_occupancy", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomtype_name", models.CharField(max_length=100)),
                ("roomtype_code", models.BigIntegerField()),
            ],
        ),
    ]
