# Generated by Django 4.2 on 2023-05-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_roomcateory_roomtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="show_time_code",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_code",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type_code",
            field=models.BigIntegerField(),
        ),
    ]
